### ISSUE TITLE
会被封号吗

### ISSUE THREAD

**Issue by LenMotion** [genchsusu/xddq-assistant#1]

**Comment by LenMotion** [comment]
serverId是指 区服的名字吗

**Comment by genchsusu** [comment]
> serverId是指 区服的名字吗

嗯 一串数字

封号就不玩呗，这种吃相难看，全是抽奖的游戏有啥意思...

我自己在拿cocos2d做口袋妖怪了，后面跟几个基友一起玩

**Comment by hello-billy** [comment]
区服数字需要自己抓包吗，在界面没有看到，想试试

**Comment by LenMotion** [comment]
> > serverId是指 区服的名字吗
> 
> 嗯 一串数字
> 
> 封号就不玩呗，这种吃相难看，全是抽奖的游戏有啥意思...
> 
> 我自己在拿cocos2d做口袋妖怪了，后面跟几个基友一起玩

怎么拿区服id呢？

**Comment by genchsusu** [comment]
> > > serverId是指 区服的名字吗
> > 
> > 
> > 嗯 一串数字
> > 封号就不玩呗，这种吃相难看，全是抽奖的游戏有啥意思...
> > 我自己在拿cocos2d做口袋妖怪了，后面跟几个基友一起玩
> 
> 怎么拿区服id呢？

```
import requests

headers = {
 'content-type':'application/json',
}

uri = "https://login-xddq.hdnd01.com/server/getAllServerName"
response0 = requests.request("POST", uri, headers=headers, data={"channelId":31})
```

**Comment by LenMotion** [comment]
> > > > serverId是指 区服的名字吗
> > > 
> > > 
> > > 嗯 一串数字
> > > 封号就不玩呗，这种吃相难看，全是抽奖的游戏有啥意思...
> > > 我自己在拿cocos2d做口袋妖怪了，后面跟几个基友一起玩
> > 
> > 
> > 怎么拿区服id呢？
> 
> ```
> import requests
> import json
> 
> headers = {
>     'xweb_xhr': '1',
>     'content-type': 'application/json',
> }
> 
> uri = "https://login-xddq.hdnd01.com/server/getAllServerName"
> payload = {"channelId": 31}
> response0 = requests.post(uri, headers=headers, json=payload, verify=False)
> 
> print(response0.text)
> ```

谢谢
