### ISSUE TITLE
Bug Fix

### ISSUE THREAD

**Issue by imzhongqi** [genchsusu/xddq-assistant#100]
在 UnionMgr.js 这个文件中

```js
            // 非周末才执行讨伐任务
            if (new Date().getDay() !== 6 && new Date().getDay() !== 0) {
                logger.debug("[妖盟管理] 妖盟讨伐 请求砍价数据");
                GameNetMgr.inst.sendPbMsg(Protocol.S_CUT_PRICE_SYNC, {}); // 这里是无法主动请求的，因为没有 cmMethod
                logger.debug("[妖盟管理] 妖盟讨伐 主动请求妖盟讨伐");
                GameNetMgr.inst.sendPbMsg(Protocol.S_UNION_BOSS_ENTER, {});
                logger.debug("[妖盟管理] 妖盟讨伐 领取妖盟讨伐奖励");
                GameNetMgr.inst.sendPbMsg(Protocol.S_UNION_BOSS_GET_REWARD_INFO, {});
            }
```
请修复一下

**Comment by genchsusu** [comment]
不会，有的。
    "CutPrice": [
        {
            "key": "S_CUT_PRICE_SYNC",
            "comment": "砍价数据同步",
            "smMethod": "CutPriceDataMsg"
        },
        {
            "key": "S_CUT_PRICE_BARGAIN",
            "comment": "砍价",
            "cmMethod": "CutPriceBargainReqMsg",
            "smMethod": "CutPriceBargainRespMsg"
        },
        {
            "key": "S_CUT_PRICE_BUY",
            "comment": "砍价购买",
            "cmMethod": "CutPriceBuyReqMsg",
            "smMethod": "CutPriceBuyRespMsg"
        }
    ]

**Comment by imzhongqi** [comment]
S_CUT_PRICE_SYNC 这玩意，没有 cmMethod，我跑的时候，这 encode 报错了
