### ISSUE TITLE
脚本执行老是卡住不动

### ISSUE THREAD

**Issue by k1z** [genchsusu/xddq-assistant#18]
![image](https://github.com/user-attachments/assets/c0c6be40-19e9-42db-bccf-f6d39dd35776)
![image](https://github.com/user-attachments/assets/bebe5f41-f755-401c-913b-01d650baa026)

就这种好像也没退出， 但是也没有任何提示了。  然后好像开启了自动砍树， 也没砍过树

**Comment by genchsusu** [comment]
你手机端顶号了呀...

**Comment by k1z** [comment]
> 你手机端顶号了呀...

应该不是， 上班时间。 。压根没看过

**Comment by YouKnowMyEggs** [comment]
自动砍树是不是只有有分身才能用，我的也不砍树

**Comment by genchsusu** [comment]
> 自动砍树是不是只有有分身才能用，我的也不砍树

是的 非分身 逻辑一样但我没写

**Comment by z0ffy** [comment]
> > 自动砍树是不是只有有分身才能用，我的也不砍树
> 
> 是的 非分身 逻辑一样但我没写

大佬有计划更上么
