### ISSUE TITLE
砍树装备属性问题

### ISSUE THREAD

**Issue by luzzhong** [genchsusu/xddq-assistant#19]
主属性和副属性怎么同时设置啊，比如我希望这个装备是[暴击抗闪，连击抗闪]，我这里condition设置的连击，暴击，抗闪，结果出来的全不对
 separation: {
            quality: 21,          // 最低品质
            fightValueOffset: 0.2,  // 妖力偏移值 能接受妖力低于该百分比 新装备妖力 >= 当前装备妖力 * ( 1 - fightValueOffset )
            probOffset: 0.2,      // 概率偏移值 概率大于该百分比直接穿上 比如当前是 16% 的概率 设置为0.1 那么大于16% x ( 1 + 0.2 ) = 19.2%
            condition:[
                [6,7,14],              // 元体
                [9,11],           // 阳神 连爆
                [6,7,12]               // 阴身 闪避
            ]
        },

**Comment by luzzhong** [comment]
fightValueOffset这个妖力偏移应该如何设置只大于当前妖力？这里的probOffset概率没太理解是什么意思

**Comment by genchsusu** [comment]
> fightValueOffset这个妖力偏移应该如何设置只大于当前妖力？这里的probOffset概率没太理解是什么意思

fightValueOffset = 0  就是必须必当前妖力高
probOffset 概率比现在高 就无视妖力直接穿

**Comment by flower-wzh** [comment]
![1722088432689](https://github.com/user-attachments/assets/79d2dedc-a3e4-4345-907e-916af012f832)
大佬，现在镇妖塔还不会打是啥问题呀
