### ISSUE TITLE
更新后不能跑任务了

### ISSUE THREAD

**Issue by Pa55w0rd** [genchsusu/xddq-assistant#23]
今天更新后，已经修改了account.json文件，执行程序只能登录游戏，不能做任务
![image](https://github.com/user-attachments/assets/5aeabe69-1a46-4530-a9c5-6a1ac37f01d7)

account.json更改内容
![image](https://github.com/user-attachments/assets/917c010c-9ca0-4269-9735-5ed1672e6bca)

**Comment by Pa55w0rd** [comment]
好吧，已经在跑任务了，新版没有打印日志不习惯

**Comment by 365360171** [comment]
> 好吧，已经在跑任务了，新版没有打印日志不习惯

```shell
tail -f logs/日志.log
``` 
就可以实时更新日志

**Comment by nzljcn** [comment]
怎么修改account.json文件
