### ISSUE TITLE
关于砍树的疑问

### ISSUE THREAD

**Issue by flower-wzh** [genchsusu/xddq-assistant#29]
我设置的
元体 闪
阳身 连爆反
阴身 反
最后阴身的反击没有给到装备，是因为跟阳身的反冲突了吗？还是我配置的有问题？
不知道有没有大佬解答一下

**Comment by zy946894123** [comment]
大佬想问下，为啥我一直重连呢？

**Comment by flower-wzh** [comment]
> 大佬想问下，为啥我一直重连呢？

是不是登录成功之后秒掉？你可以提供一下你的日志

**Comment by zy946894123** [comment]
![Uploading 333.png…]()

**Comment by zy946894123** [comment]
yarn install v1.22.22
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.11s.
yarn run v1.22.22
$ node app.js
2024-08-09 15:13:34.642 info   [守护] 父进程的 PID: 25408
2024-08-09 15:13:34.655 info   [守护] 启动 3112510区的 ****** PID: 24516
2024-08-09 15:13:36.166 warn   [守护] 子进程退出，将在 2024/8/9 15:18:36 重启 (重连次数: 1/5)
2024-08-09 15:13:36.168 info   [守护] 杀死 3112510区的 ***** PID: 24516
服务器ID 账号密码都配置了的

**Comment by zy946894123** [comment]
看了日志，是的，登录成功后秒退

**Comment by genchsusu** [comment]
玉鼎山10服 logs里有详细日志 大概率是配置不正确导致的。

**Comment by genchsusu** [comment]
> 我设置的 元体 闪 阳身 连爆反 阴身 反 最后阴身的反击没有给到装备，是因为跟阳身的反冲突了吗？还是我配置的有问题？ 不知道有没有大佬解答一下

用strict模式。

**Comment by flower-wzh** [comment]
> > 我设置的 元体 闪 阳身 连爆反 阴身 反 最后阴身的反击没有给到装备，是因为跟阳身的反冲突了吗？还是我配置的有问题？ 不知道有没有大佬解答一下
> 
> 用strict模式。

strict模式的secondaryAttribute是不是只能设置抗性？

**Comment by flower-wzh** [comment]
> 玉鼎山10服 logs里有详细日志 大概率是配置不正确导致的。

大佬可以看下Q&A里边好多人反映这个

**Comment by flower-wzh** [comment]
> > 我设置的 元体 闪 阳身 连爆反 阴身 反 最后阴身的反击没有给到装备，是因为跟阳身的反冲突了吗？还是我配置的有问题？ 不知道有没有大佬解答一下
> 
> 用strict模式。
"strictConditions": [
                    {
                        "primaryAttribute": [
                            8
                        ],
                        "secondaryAttribute": [
                            12
                        ]
                    },
                    {
                        "primaryAttribute": [
                            6,
                            7,
                            9
                        ],
                        "secondaryAttribute": [
                            14
                        ]
                    },
                    {
                        "primaryAttribute": [
                            9
                        ],
                        "secondaryAttribute": [
                            11
                        ]
                    }
                ]
我这样配置的阴身还是没有装备穿上，我阴身身上没有什么装备应该不是属性太低的问题

**Comment by genchsusu** [comment]
> 我阴身身上没有什么装备应该不是属性太低的问题

不会 我设置的 纯反抗晕 连反爆抗闪 纯闪抗晕抗暴 能工作。
