### ISSUE TITLE
启动之后直接被杀死了，除了账号密码还有什么要填吗

### ISSUE THREAD

**Issue by unknowkaf** [genchsusu/xddq-assistant#37]
yarn start
yarn run v1.22.22
$ node app.js
2024-08-13 17:25:20.064 info   [守护] 父进程的 PID: 1548
2024-08-13 17:25:20.072 info   [守护] 启动 <3112524>区的 <504d> PID: 16536
2024-08-13 17:25:20.626 warn   [守护] 子进程退出，将在 2024/8/13 17:30:20 重启 (重连次数: 1/5)
2024-08-13 17:25:20.627 info   [守护] 杀死 <3112524>区的 <504d> PID: 16536

**Comment by 365360171** [comment]
区服没填吧

**Comment by Wislove** [comment]
fildder抓了包，应该是请求了什么活动数据，客户端没有响应，然后就断了。我不太会node。这里有个简单的处理方式，我这边暂时能用的方式。就是在启动的时候，先把LoopMgr里面的start启动时间间隔调大一点，调个把原来的1000毫秒调成10秒，把switch里面所有控制先关了。先启动起来，等广告任务执行完了。然后再重启，打开砍树那些开关

**Comment by Wislove** [comment]
应该是某个请求，在第一次登录的时候，要间隔好多秒以上才能请求。我试着在启动的时候，增加一个sleep看看效果

**Comment by Pa55w0rd** [comment]
> fildder抓了包，应该是请求了什么活动数据，客户端没有响应，然后就断了。我不太会node。这里有个简单的处理方式，我这边暂时能用的方式。就是在启动的时候，先把LoopMgr里面的start启动时间间隔调大一点，调个把原来的1000毫秒调成10秒，把switch里面所有控制先关了。先启动起来，等广告任务执行完了。然后再重启，打开砍树那些开关

谢谢大佬，我按照你的方法可以运行了

**Comment by unknowkaf** [comment]
> > fildder抓了包，应该是请求了什么活动数据，客户端没有响应，然后就断了。 我不太会node。 这里有个简单的处理方式，我这边暂时能用的方式。 就是在启动的时候，先把LoopMgr里面的start启动时间间隔调大一点，调个把原来的1000毫秒调成10秒，把switch里面所有控制先关了。 先启动起来，等广告任务执行完了。 然后再重启，打开砍树那些开关
> 
> 谢谢大佬，我按照你的方法可以运行了

你有填写区服吗？sever id需要什么办法读取吗，我也按照这个方法修改了，结果还是一样的

**Comment by zy946894123** [comment]
可以的，我也能执行了

**Comment by Pa55w0rd** [comment]
> fildder抓了包，应该是请求了什么活动数据，客户端没有响应，然后就断了。我不太会node。这里有个简单的处理方式，我这边暂时能用的方式。就是在启动的时候，先把LoopMgr里面的start启动时间间隔调大一点，调个把原来的1000毫秒调成10秒，把switch里面所有控制先关了。先启动起来，等广告任务执行完了。然后再重启，打开砍树那些开关

时间长了也会断

**Comment by zy946894123** [comment]
2024-08-13 15:22:15.757 info   [广告管理] 执行任务 [灵兽内丹] 还剩 2 次广告激励
2024-08-13 15:22:15.758 info   [广告管理] 增加待执行任务 211706  [灵兽内丹] 还剩 2 次广告激励
2024-08-13 15:22:25.759 info   [广告管理] 增加待执行任务 211706  [灵兽内丹] 还剩 2 次广告激励
会一直卡这个任务

**Comment by unknowkaf** [comment]
> > fildder抓了包，应该是请求了什么活动数据，客户端没有响应，然后就断了。我不太会node。这里有个简单的处理方式，我这边暂时能用的方式。就是在启动的时候，先把LoopMgr里面的start启动时间间隔调大一点，调个把原来的1000毫秒调成10秒，把switch里面所有控制先关了。先启动起来，等广告任务执行完了。然后再重启，打开砍树那些开关
> 
> 时间长了也会断

loopmgr里是修改哪一行的时间啊，几个timeout修改了都不行

**Comment by unknowkaf** [comment]
> fildder抓了包，应该是请求了什么活动数据，客户端没有响应，然后就断了。我不太会node。这里有个简单的处理方式，我这边暂时能用的方式。就是在启动的时候，先把LoopMgr里面的start启动时间间隔调大一点，调个把原来的1000毫秒调成10秒，把switch里面所有控制先关了。先启动起来，等广告任务执行完了。然后再重启，打开砍树那些开关

大佬，loopmgr中具体该如何修改可以讲一下吗，我看不出哪个是启动时间啊

**Comment by genchsusu** [comment]
缺个关键性判断，提前使用了未打开的功能会导致封号。

//     // 102 系统解锁同步
//     static SystemUnlockSync(t) {
//         logger.debug("[MsgRecvMgr] 系统解锁同步");
//         SystemUnlockMgr.inst.SystemUnlockSync(t);
//     }
