### ISSUE TITLE
关于start.bat无法在win11下运行。请指导

### ISSUE THREAD

**Issue by nzljcn** [genchsusu/xddq-assistant#41]
+ FullyQualifiedErrorId : CommandNotFoundException

Suggestion [3,General]: 找不到命令 start.bat，但它确实存在于当前位置。默认情况下，Windows PowerShell 不会从当前位置加载 命令。如果信任此命令，请改为键入“.\start.bat”。有关详细信息，请参阅 "get-help about_Command_Precedence"。
PS C:\Users\aaa\Desktop\xddq\01laomao> .\start.bat
'惎鍔ㄧ殑' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'ime' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'鏃跺拰鍒嗛挓鐨勫墠瀵奸浂' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'"23"' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'hell' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'"        if ($commandLine -like $searchPattern) {"' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'rocessId)'' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'gFile' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'eout' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'/t' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'p' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'柇' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'璇诲彇' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'r' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
缁堟 yarn 杩涚▼ %I...
C:\Users\aaa\Desktop\xddq\01laomao\*, 是否确认(Y/N)? n
PS C:\Users\aaa\Desktop\xddq\01laomao>

**Comment by luzzhong** [comment]
win11没有尝试😂，先用原来的方式吧

**Comment by genchsusu** [comment]
> win11没有尝试😂，先用原来的方式吧

等我道心稳固了，写个exe版本的。

**Comment by luzzhong** [comment]
> > win11没有尝试😂，先用原来的方式吧
> 
> 等我道心稳固了，写个exe版本的。

可以，先兼容大部分，在慢慢针对性优化

**Comment by luzzhong** [comment]
> ```
> + FullyQualifiedErrorId : CommandNotFoundException
> ```
> 
> Suggestion [3,General]: 找不到命令 start.bat，但它确实存在于当前位置。默认情况下，Windows PowerShell 不会从当前位置加载 命令。如果信任此命令，请改为键入“.\start.bat”。有关详细信息，请参阅 "get-help about_Command_Precedence"。 PS C:\Users\aaa\Desktop\xddq\01laomao> .\start.bat '惎鍔ㄧ殑' 不是内部或外部命令，也不是可运行的程序 或批处理文件。 'ime' 不是内部或外部命令，也不是可运行的程序 或批处理文件。 '鏃跺拰鍒嗛挓鐨勫墠瀵奸浂' 不是内部或外部命令，也不是可运行的程序 或批处理文件。 '"23"' 不是内部或外部命令，也不是可运行的程序 或批处理文件。 'hell' 不是内部或外部命令，也不是可运行的程序 或批处理文件。 '" if ($commandLine -like $searchPattern) {"' 不是内部或外部命令，也不是可运行的程序 或批处理文件。 'rocessId)'' 不是内部或外部命令，也不是可运行的程序 或批处理文件。 'gFile' 不是内部或外部命令，也不是可运行的程序 或批处理文件。 'eout' 不是内部或外部命令，也不是可运行的程序 或批处理文件。 '/t' 不是内部或外部命令，也不是可运行的程序 或批处理文件。 'p' 不是内部或外部命令，也不是可运行的程序 或批处理文件。 '柇' 不是内部或外部命令，也不是可运行的程序 或批处理文件。 '璇诲彇' 不是内部或外部命令，也不是可运行的程序 或批处理文件。 'r' 不是内部或外部命令，也不是可运行的程序 或批处理文件。 缁堟 yarn 杩涚▼ %I... C:\Users\aaa\Desktop\xddq\01laomao*, 是否确认(Y/N)? n PS C:\Users\aaa\Desktop\xddq\01laomao>
辛苦用这个验证一下

`@echo off  
chcp 65001 > nul  
setlocal enabledelayedexpansion  
  
set "logFile=%~dp0kill_log.txt"  
set "yarnPIDFile=%~dp0yarn_pid.txt"  
  
echo Starting yarn...  
start "" /b cmd /c "yarn start" >nul 2>&1  
  
for /f "tokens=2" %%A in ('wmic process where "commandline like '%%yarn start%%'" get ProcessId') do (  
    echo %%A > "%yarnPIDFile%"  
)  
  
:loop  
for /f "tokens=1-2 delims=:" %%A in ("%time:~0,5%") do (  
    set "hour=%%A"  
    set "minute=%%B"  
    set "hour=!hour:~-2!"  
    set "minute=!minute:~-2!"  
)  
  
if "!hour!"=="23" if "!minute!"=="57" (  
    echo Executing PowerShell script...  
    powershell -ExecutionPolicy Bypass -Command "$searchPattern = '.*\\src\\index.js'; $processes = Get-WmiObject Win32_Process | Where-Object { $_.Name -eq 'node.exe' -and $_.CommandLine -like $searchPattern }; foreach ($process in $processes) { try { Write-Output 'Terminating process ID $($process.ProcessId) command line: $($process.CommandLine)'; Stop-Process -Id $process.ProcessId -Force; } catch { Write-Output 'Failed to terminate process ID $($process.ProcessId)'; } }" > "%logFile%" 2>&1  
    echo Done, output saved to %logFile%  
    timeout /t 60 /nobreak >nul  
)  
  
timeout /t 10 /nobreak >nul  
goto loop  
  
:handleCtrlC  
if exist "%yarnPIDFile%" (  
    for /f "delims=" %%I in ("%yarnPIDFile%") do (  
        echo Terminating yarn process %%I...  
        taskkill /PID %%I /F >nul 2>&1  
    )  
    del "%yarnPIDFile%"  
)  
exit /b`

**Comment by luzzhong** [comment]
`@echo off  
chcp 65001 > nul  
setlocal enabledelayedexpansion  
  
set "logFile=%~dp0kill_log.txt"  
set "yarnPIDFile=%~dp0yarn_pid.txt"  
  
echo Starting yarn...  
start "" /b cmd /c "yarn start" >nul 2>&1  
  
for /f "tokens=2" %%A in ('wmic process where "commandline like '%%yarn start%%'" get ProcessId') do (  
    echo %%A > "%yarnPIDFile%"  
)  
  
:loop  
for /f "tokens=1-2 delims=:" %%A in ("%time:~0,5%") do (  
    set "hour=%%A"  
    set "minute=%%B"  
    set "hour=!hour:~-2!"  
    set "minute=!minute:~-2!"  
)  
  
if "!hour!"=="23" if "!minute!"=="57" (  
    echo Executing PowerShell script...  
    powershell -ExecutionPolicy Bypass -Command "$searchPattern = '.*\\src\\index.js'; $processes = Get-WmiObject Win32_Process | Where-Object { $_.Name -eq 'node.exe' -and $_.CommandLine -like $searchPattern }; foreach ($process in $processes) { try { Write-Output 'Terminating process ID $($process.ProcessId) command line: $($process.CommandLine)'; Stop-Process -Id $process.ProcessId -Force; } catch { Write-Output 'Failed to terminate process ID $($process.ProcessId)'; } }" > "%logFile%" 2>&1  
    echo Done, output saved to %logFile%  
    timeout /t 60 /nobreak >nul  
)  
  
timeout /t 10 /nobreak >nul  
goto loop  
  
:handleCtrlC  
if exist "%yarnPIDFile%" (  
    for /f "delims=" %%I in ("%yarnPIDFile%") do (  
        echo Terminating yarn process %%I...  
        taskkill /PID %%I /F >nul 2>&1  
    )  
    del "%yarnPIDFile%"  
)  
exit /b`

**Comment by luzzhong** [comment]
> ```
> + FullyQualifiedErrorId : CommandNotFoundException
> ```
> 
> Suggestion [3,General]: 找不到命令 start.bat，但它确实存在于当前位置。默认情况下，Windows PowerShell 不会从当前位置加载 命令。如果信任此命令，请改为键入“.\start.bat”。有关详细信息，请参阅 "get-help about_Command_Precedence"。 PS C:\Users\aaa\Desktop\xddq\01laomao> .\start.bat '惎鍔ㄧ殑' 不是内部或外部命令，也不是可运行的程序 或批处理文件。 'ime' 不是内部或外部命令，也不是可运行的程序 或批处理文件。 '鏃跺拰鍒嗛挓鐨勫墠瀵奸浂' 不是内部或外部命令，也不是可运行的程序 或批处理文件。 '"23"' 不是内部或外部命令，也不是可运行的程序 或批处理文件。 'hell' 不是内部或外部命令，也不是可运行的程序 或批处理文件。 '" if ($commandLine -like $searchPattern) {"' 不是内部或外部命令，也不是可运行的程序 或批处理文件。 'rocessId)'' 不是内部或外部命令，也不是可运行的程序 或批处理文件。 'gFile' 不是内部或外部命令，也不是可运行的程序 或批处理文件。 'eout' 不是内部或外部命令，也不是可运行的程序 或批处理文件。 '/t' 不是内部或外部命令，也不是可运行的程序 或批处理文件。 'p' 不是内部或外部命令，也不是可运行的程序 或批处理文件。 '柇' 不是内部或外部命令，也不是可运行的程序 或批处理文件。 '璇诲彇' 不是内部或外部命令，也不是可运行的程序 或批处理文件。 'r' 不是内部或外部命令，也不是可运行的程序 或批处理文件。 缁堟 yarn 杩涚▼ %I... C:\Users\aaa\Desktop\xddq\01laomao*, 是否确认(Y/N)? n PS C:\Users\aaa\Desktop\xddq\01laomao>

下载一下这个试试没问题我在合入分支：https://github.com/luzzhong/xddq-assistant/blob/master/start.bat

**Comment by luzzhong** [comment]
`bat
@echo off  
chcp 65001 > nul  
setlocal enabledelayedexpansion  
  
set "logFile=%~dp0kill_log.txt"  
set "yarnPIDFile=%~dp0yarn_pid.txt"  
  
echo Starting yarn...  
start "" /b cmd /c "yarn start" >nul 2>&1  
  
for /f "tokens=2" %%A in ('wmic process where "commandline like '%%yarn start%%'" get ProcessId') do (  
    echo %%A > "%yarnPIDFile%"  
)  
  
:loop  
for /f "tokens=1-2 delims=:" %%A in ("%time:~0,5%") do (  
    set "hour=%%A"  
    set "minute=%%B"  
    set "hour=!hour:~-2!"  
    set "minute=!minute:~-2!"  
)  
  
if "!hour!"=="23" if "!minute!"=="57" (  
    echo Executing PowerShell script...  
    powershell -ExecutionPolicy Bypass -Command "$searchPattern = '.*\\src\\index.js'; $processes = Get-WmiObject Win32_Process | Where-Object { $_.Name -eq 'node.exe' -and $_.CommandLine -like $searchPattern }; foreach ($process in $processes) { try { Write-Output 'Terminating process ID $($process.ProcessId) command line: $($process.CommandLine)'; Stop-Process -Id $process.ProcessId -Force; } catch { Write-Output 'Failed to terminate process ID $($process.ProcessId)'; } }" > "%logFile%" 2>&1  
    echo Done, output saved to %logFile%  
    timeout /t 60 /nobreak >nul  
)  
  
timeout /t 10 /nobreak >nul  
goto loop  
  
:handleCtrlC  
if exist "%yarnPIDFile%" (  
    for /f "delims=" %%I in ("%yarnPIDFile%") do (  
        echo Terminating yarn process %%I...  
        taskkill /PID %%I /F >nul 2>&1  
    )  
    del "%yarnPIDFile%"  
)  
exit /b
`

**Comment by luzzhong** [comment]
``` @echo off  
chcp 65001 > nul  
setlocal enabledelayedexpansion  
  
set "logFile=%~dp0kill_log.txt"  
set "yarnPIDFile=%~dp0yarn_pid.txt"  
  
echo Starting yarn...  
start "" /b cmd /c "yarn start" >nul 2>&1  
  
for /f "tokens=2" %%A in ('wmic process where "commandline like '%%yarn start%%'" get ProcessId') do (  
    echo %%A > "%yarnPIDFile%"  
)  
  
:loop  
for /f "tokens=1-2 delims=:" %%A in ("%time:~0,5%") do (  
    set "hour=%%A"  
    set "minute=%%B"  
    set "hour=!hour:~-2!"  
    set "minute=!minute:~-2!"  
)  
  
if "!hour!"=="23" if "!minute!"=="57" (  
    echo Executing PowerShell script...  
    powershell -ExecutionPolicy Bypass -Command "$searchPattern = '.*\\src\\index.js'; $processes = Get-WmiObject Win32_Process | Where-Object { $_.Name -eq 'node.exe' -and $_.CommandLine -like $searchPattern }; foreach ($process in $processes) { try { Write-Output 'Terminating process ID $($process.ProcessId) command line: $($process.CommandLine)'; Stop-Process -Id $process.ProcessId -Force; } catch { Write-Output 'Failed to terminate process ID $($process.ProcessId)'; } }" > "%logFile%" 2>&1  
    echo Done, output saved to %logFile%  
    timeout /t 60 /nobreak >nul  
)  
  
timeout /t 10 /nobreak >nul  
goto loop  
  
:handleCtrlC  
if exist "%yarnPIDFile%" (  
    for /f "delims=" %%I in ("%yarnPIDFile%") do (  
        echo Terminating yarn process %%I...  
        taskkill /PID %%I /F >nul 2>&1  
    )  
    del "%yarnPIDFile%"  
)  
exit /b
```

**Comment by luzzhong** [comment]
```
@echo off  
chcp 65001 > nul  
setlocal enabledelayedexpansion  
  
set "logFile=%~dp0kill_log.txt"  
set "yarnPIDFile=%~dp0yarn_pid.txt"  
  
echo Starting yarn...  
start "" /b cmd /c "yarn start" >nul 2>&1  
  
for /f "tokens=2" %%A in ('wmic process where "commandline like '%%yarn start%%'" get ProcessId') do (  
    echo %%A > "%yarnPIDFile%"  
)  
  
:loop  
for /f "tokens=1-2 delims=:" %%A in ("%time:~0,5%") do (  
    set "hour=%%A"  
    set "minute=%%B"  
    set "hour=!hour:~-2!"  
    set "minute=!minute:~-2!"  
)  
  
if "!hour!"=="23" if "!minute!"=="57" (  
    echo Executing PowerShell script...  
    powershell -ExecutionPolicy Bypass -Command "$searchPattern = '.*\\src\\index.js'; $processes = Get-WmiObject Win32_Process | Where-Object { $_.Name -eq 'node.exe' -and $_.CommandLine -like $searchPattern }; foreach ($process in $processes) { try { Write-Output 'Terminating process ID $($process.ProcessId) command line: $($process.CommandLine)'; Stop-Process -Id $process.ProcessId -Force; } catch { Write-Output 'Failed to terminate process ID $($process.ProcessId)'; } }" > "%logFile%" 2>&1  
    echo Done, output saved to %logFile%  
    timeout /t 60 /nobreak >nul  
)  
  
timeout /t 10 /nobreak >nul  
goto loop  
  
:handleCtrlC  
if exist "%yarnPIDFile%" (  
    for /f "delims=" %%I in ("%yarnPIDFile%") do (  
        echo Terminating yarn process %%I...  
        taskkill /PID %%I /F >nul 2>&1  
    )  
    del "%yarnPIDFile%"  
)  
exit /b
```
