### ISSUE TITLE
自动断开问题统一解答

### ISSUE THREAD

**Issue by genchsusu** [genchsusu/xddq-assistant#45]
1. JSON格式出错
2. 缺少关键性判断，提前使用了未激活的功能会导致封号。

// 102 系统解锁同步
static SystemUnlockSync(t) {
 logger.debug("[MsgRecvMgr] 系统解锁同步");
 SystemUnlockMgr.inst.SystemUnlockSync(t);
}

**Comment by Pa55w0rd** [comment]
大佬，有计划添加这个判断么

**Comment by genchsusu** [comment]
<img width="450" alt="image" src="https://github.com/user-attachments/assets/89422528-fb1e-419a-a904-693edad58c39">
<img width="450" alt="image" src="https://github.com/user-attachments/assets/9721f696-dc9d-4225-8180-0a8b5a919fab">
<img width="450" alt="image" src="https://github.com/user-attachments/assets/db9e3668-92be-4bd7-896f-460daf05ca9e">
我在写这个

**Comment by e15452e** [comment]
我这边发现只要在100-300毫秒内发送请求5次就会自动断开
这跟我之前在宗门自动修炼太快也会报  "操作太快,请稍后重试"  一样
另外,不同的功能全部一起发送请求也会断开,建议每一个功能都分隔100ms一个一个发

**Comment by e15452e** [comment]
![image](https://github.com/user-attachments/assets/138cda3b-039c-404d-bdba-a59dfb13bf6c)

**Comment by genchsusu** [comment]
> 大佬，有计划添加这个判断么，我现在已经回退到[5bb4e5a](https://github.com/genchsusu/xddq-assistant/tree/5bb4e5a50f91889d0355ab3cfd4e89dd8f5c202f)临时使用是正常的

之前冲动把反编译出来资料全删了- -，最近在恶学Rust没空弄，实际上把MsgRecvMgr.js部分功能注释掉就ok了。

**Comment by Pa55w0rd** [comment]
> > 大佬，有计划添加这个判断么，我现在已经回退到[5bb4e5a](https://github.com/genchsusu/xddq-assistant/tree/5bb4e5a50f91889d0355ab3cfd4e89dd8f5c202f)临时使用是正常的
> 
> 之前冲动把反编译出来资料全删了- -，最近在恶学Rust没空弄，实际上把MsgRecvMgr.js部分功能注释掉就ok了。

按照大佬说的，提前使用未开启的功能会导致封号，我就是这个现象，我把PlayerPetDataSync和PetKernelDrawResp注释掉了，还是会导致封号，这个就不纠结了，先退回旧版本使用了，羡慕大佬说学一门编程语言就学，我从大学就在学python/go/java，到现在工作8年了也没学会，主要是学了不用就会忘记，用还用不好

**Comment by nzljcn** [comment]
> 1. JSON格式出错
> 2. 缺少关键性判断，提前使用了未激活的功能会导致封号。
> 
> // 102 系统解锁同步 static SystemUnlockSync(t) { logger.debug("[MsgRecvMgr] 系统解锁同步"); SystemUnlockMgr.inst.SystemUnlockSync(t); }

刚出分身的角色，开砍树也会出现秒断。请教什么问题。

**Comment by xyloneX** [comment]
> <img alt="image" width="450" src="https://private-user-images.githubusercontent.com/45809485/359030096-89422528-fb1e-419a-a904-693edad58c39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMTk1NzYsIm5iZiI6MTcyNDMxOTI3NiwicGF0aCI6Ii80NTgwOTQ4NS8zNTkwMzAwOTYtODk0MjI1MjgtZmIxZS00MTlhLWE5MDQtNjkzZWRhZDU4YzM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDA5MzQzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyYThkYjg3OWM4YzhmYTNkZjczMjdhODc2YzhjMWVmYzRhY2QzODUxMTcyMTk0NjVkYjIxZGE4ZjBlNWYyZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RJmg5v1pM02B4FCjg2EaP3LFrqoTTGuIjyE2HTknGAQ"> <img alt="image" width="450" src="https://private-user-images.githubusercontent.com/45809485/359030126-9721f696-dc9d-4225-8180-0a8b5a919fab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMTk1NzYsIm5iZiI6MTcyNDMxOTI3NiwicGF0aCI6Ii80NTgwOTQ4NS8zNTkwMzAxMjYtOTcyMWY2OTYtZGM5ZC00MjI1LTgxODAtMGE4YjVhOTE5ZmFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDA5MzQzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4MTQyZjJjMWJhZWIxMGY5ZTNmNjllMDdjYTRlNTljMmEyOTRkNzllNjRmOWY3ZGI1ODdiNzgzNGJhNDg1MGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6JftVVbDNpniDFPdw-8NJ3VGaldl51uW94f8QaqaSEM"> <img alt="image" width="450" src="https://private-user-images.githubusercontent.com/45809485/359030190-db9e3668-92be-4bd7-896f-460daf05ca9e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMTk1NzYsIm5iZiI6MTcyNDMxOTI3NiwicGF0aCI6Ii80NTgwOTQ4NS8zNTkwMzAxOTAtZGI5ZTM2NjgtOTJiZS00YmQ3LTg5NmYtNDYwZGFmMDVjYTllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDA5MzQzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3MDFiMDE1NzFkYjc0NTM3ZmU5M2M2YWU4OGFiN2ZkOTYxYWZlYjE0ZjI5YzU2ODEzNzc3NjNlOTJhYTBhZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OmpUZp_yYAlbA1gmtK7iVt3LZA1wDCxWybzkY6PqBX0">
> 我在写这个，没精力管这边代码。

太帅了
