### ISSUE TITLE
刚上线就断开连接了

### ISSUE THREAD

**Issue by hcandy** [genchsusu/xddq-assistant#52]
应该是刚登录那一下的数据包发送的太快了 有没有哪里设置发包的频率?没有的话写在那里比较好

**Comment by zhouerfu77322** [comment]
> 应该是刚登录那一下的数据包发送的太快了 有没有哪里设置发包的频率?没有的话写在那里比较好
#45

**Comment by hcandy** [comment]
> > 应该是刚登录那一下的数据包发送的太快了 有没有哪里设置发包的频率?没有的话写在那里比较好
> > #45

我看了这里的代码好像就是已经注释掉的,我在发送消息的地方加了一个队列 发送消息添加到队列 每隔100ms发送一个消息就不会断了

**Comment by nzljcn** [comment]
> > > 应该是刚登录那一下的数据包发送的太快了 有没有哪里设置发包的频率?没有的话写在那里比较好
> > > #45
> 
> 我看了这里的代码好像就是已经注释掉的,我在发送消息的地方加了一个队列 发送消息添加到队列 每隔100ms发送一个消息就不会断了

求代码

**Comment by Pa55w0rd** [comment]
> > > > 应该是刚登录那一下的数据包发送的太快了 有没有哪里设置发包的频率?没有的话写在那里比较好
> > > > #45
> > 
> > 
> > 我看了这里的代码好像就是已经注释掉的,我在发送消息的地方加了一个队列 发送消息添加到队列 每隔100ms发送一个消息就不会断了
> 
> 求代码

src\game\net\GameNetMgr.js
const messageQueue = []; // 创建消息队列
let isSending = false; // 标记是否正在发送消息

class GameNetMgr {
....
    sendPbMsg(msgId, msgData, callback, extraCmd, directSend = false) {
        if (!this.net.isConnected()) {
            return;
        }

        const stream = new Stream();
        stream.init(msgId, +this.playerId, NetSocket.BYTES_OF_MSG_HEADER + NetSocket.MSG_DATA_LENGTH, true);
        stream.writeShort(NetSocket.HEADER);
        stream.writeInt(50);
        stream.writeInt(msgId);
        stream.writeLong(this.playerId);

        if (stream.pbMsg) {
            const body = stream.pbMsg.encode(msgData).finish();
            stream.writeBytes(body, 18);
        }

        stream.writeInt(stream.offset, 2);
        const t = new Uint8Array(stream.offset);
        t.set(stream.buff.subarray(0, stream.offset));
        stream.buff = t;
        stream.streamsize = stream.offset;

        const protoCmd = ProtobufMgr.inst.cmdList[msgId];
        if (callback && this.net.isConnected()) {
            this.addHandler(protoCmd.smMsgId, callback);
        }

        if (extraCmd && ProtobufMgr.inst.cmdList[extraCmd]) {
            this.addHandler(extraCmd, callback);
        }

        // 如果 directSend 为 true，直接发送，否则将消息添加到队列
        if (directSend) {
            this.net.send(stream.buff);
        } else {
            messageQueue.push({ msgId, msgData, callback, extraCmd });
            this.startSending();
        }
    }

    startSending() {
        if (isSending || messageQueue.length === 0) {
            return;
        }

        isSending = true;

        const sendNextMessage = () => {
            if (messageQueue.length > 0) {
                const { msgId, msgData, callback, extraCmd } = messageQueue.shift();
                this.sendPbMsg(msgId, msgData, callback, extraCmd, true);
                setTimeout(sendNextMessage, 100);
            } else {
                isSending = false;
            }
        };

        sendNextMessage();
    }
....
}
