### ISSUE TITLE
点击start无法正常启动 

### ISSUE THREAD

**Issue by Czy2019** [genchsusu/xddq-assistant#53]
![image](https://github.com/user-attachments/assets/6a576de5-69de-4acc-bb0d-466372184d4a)

**Comment by luzzhong** [comment]
这就启动了，看下日志

**Comment by Czy2019** [comment]
![image](https://github.com/user-attachments/assets/d39b95be-7b0e-42bd-a93d-1a5bd82614c7)
谢谢大佬，但是我运行的时候也没有看到有logs文件夹的生成呀

**Comment by Czy2019** [comment]
![image](https://github.com/user-attachments/assets/779ffe8f-3130-41ee-b5e9-de9a396a1efa)
还是没有生成logs文件夹 这是我的问题嘛
