### ISSUE TITLE
能否增加定时重启的相关设定

### ISSUE THREAD

**Issue by YouKnowMyEggs** [genchsusu/xddq-assistant#61]
我记得之前有一个版本每天00:00会自动重启，但现在无法自动重启，导致大部分任务无法自动完成。我是在Docker环境中使用的。

**Comment by StormZ0** [comment]
可以用docker的自动重启

**Comment by StormZ0** [comment]
![StormZ0 (15)](https://github.com/user-attachments/assets/24e9f61e-78f5-44f0-a901-b5415357cd8c)

**Comment by StormZ0** [comment]
![Uploading StormZ0 (15).png…]()

**Comment by StormZ0** [comment]
![Uploading StormZ0 (15).png…]()

**Comment by StormZ0** [comment]
![Uploading StormZ0 (15).png…]()

**Comment by StormZ0** [comment]
![StormZ0 (15)](https://github.com/user-attachments/assets/2164fcf9-314a-4e62-89e4-c5a3e785f816)

**Comment by YouKnowMyEggs** [comment]
> 可以用docker的自动重启

我想过这样，因为我设备重启docker的时间比较感人..很难卡准0点的时间点，总体来说就是定时重启Docker容器，然后自定义脚本执行‘nohup yarn start &’这样吧。

**Comment by StormZ0** [comment]
你做镜像的时候没有考虑时间吗

**Comment by flower-wzh** [comment]
> ![StormZ0 (15)](https://private-user-images.githubusercontent.com/30486001/363986511-2164fcf9-314a-4e62-89e4-c5a3e785f816.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1MjA1MjgsIm5iZiI6MTcyNTUyMDIyOCwicGF0aCI6Ii8zMDQ4NjAwMS8zNjM5ODY1MTEtMjE2NGZjZjktMzE0YS00ZTYyLTg5ZTQtYzVhM2U3ODVmODE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA1VDA3MTAyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5N2E2OTY4NjA1NjNlMmY3YzBmOGIxMjM3MzE3NDE3ZDNmMzU3NTI5YjhmYjk4MzY4ZGFlMjlkMzJiN2JhZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0ZysNgzQtqk-sm-3Pqp-B15FNqk2btQeBWs4Gb_B2VI)

我也用的1panel计划任务管理的🐶
