### ISSUE TITLE
仙友怎么获取到是否开始十连游历?

### ISSUE THREAD

**Issue by Shaco-Ma** [genchsusu/xddq-assistant#64]
大佬,我看你有获取this.power = t.playerDestinyDataMsg.power这个游历体力,怎么获取是否开启十连游历呢?
我把下面的改成了十连游历,是因为我开启了十连游历,希望能加一下十连游历的判断
if(this.power >= 10)
{
    logger.info(`[仙友管理] 进行游历`);
    // 一键游历 等级达到练虚
    GameNetMgr.inst.sendPbMsg(Protocol.S_DESTINY_TRAVEL, { isOneKey: PlayerAttributeMgr.bigType >= 5 }, null);
}

**Comment by Shaco-Ma** [comment]
@genchsusu 不是练虚判断啊,是<怎么判断是否开启十连游历>,另外您这个sync是多久一次啊?

**Comment by genchsusu** [comment]
> @genchsusu 不是练虚判断啊,是<怎么判断是否开启十连游历>,另外您这个sync是多久一次啊?

炼虚之后就有十连
30分钟回一格能量
