### ISSUE TITLE
冒险/真火/镇妖塔的分身选择

### ISSUE THREAD

**Issue by allran** [genchsusu/xddq-assistant#66]
关于冒险/真火/镇妖塔，这些关卡，需要切换到反击分身才行。但好像没找到关于分身的配置。

**Comment by allran** [comment]
就是ChapterMgr.js,SecretTowerMgr.js,TowerMgr.js, 这三个文件，参考InvadeMgr.js这个异兽入侵，改一下就成

**Comment by allran** [comment]
作者大大代码规范，逻辑清晰，牛得一批

**Comment by zeroT6** [comment]
我如何才能写到这么逻辑清晰的代码啊  冒险/真火/镇妖/星宿分身copy之后就可以使用了

**Comment by gyety** [comment]
大佬方便拉个群吗
