### ISSUE TITLE
yarn：bat问题

### ISSUE THREAD

**Issue by BaJie041012** [genchsusu/xddq-assistant#75]
非常抱歉又是我，我对github不太熟悉，不确定在被关闭的issue中回复是否会被您看到，所以重新开了一个issue，情况是使用您给的bat，在确保bat内容无误且使用管理员打开的情况下，两个bat都闪退了，应该没执行到pause就在中途出现了一些未知问题，不知道您是否有解决方案

**Comment by BaJie041012** [comment]
[setup.log](https://github.com/user-attachments/files/16906068/setup.log)


[start.log](https://github.com/user-attachments/files/16906070/start.log)

这是我所使用的两个bat，bat格式无法发出来所以我把后缀改为了log

**Comment by BaJie041012** [comment]
我在我的云服务器上试用了这两个bat，同样的直接闪退了

**Comment by BaJie041012** [comment]
<img width="934" alt="image" src="https://github.com/user-attachments/assets/99a5237d-18cf-4b53-91fb-106b6d52c67e">
我在我的云服务器上重新尝试了，setup.bat成功下载和解压了node.js，但start.bat仍然直接闪退了

**Comment by luzzhong** [comment]
> <img alt="image" width="934" src="https://private-user-images.githubusercontent.com/160606914/365134616-99a5237d-18cf-4b53-91fb-106b6d52c67e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MTk5NDMsIm5iZiI6MTcyNTYxOTY0MywicGF0aCI6Ii8xNjA2MDY5MTQvMzY1MTM0NjE2LTk5YTUyMzdkLTE4Y2YtNGI1My05MWZiLTEwNmI2ZDUyYzY3ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNlQxMDQ3MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00OGVkYjZlMWViN2MzZDZhNDQwMzJlYTQ2NTA3NjIxODYzMzZiMmM1ZmFkZjEwMmRiZGQ5ZDdjMzJiNDQ0ZGMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BM-fSdnxIbCIOLdiEgqRmM5jvq38acwPk-1crzORpLM"> 我在我的云服务器上重新尝试了，setup.bat成功下载和解压了node.js，但start.bat仍然直接闪退了

你都有云服务器了为啥不搞一个Linux的？搞个win是咋想的

**Comment by BaJie041012** [comment]
<img width="1280" alt="image" src="https://github.com/user-attachments/assets/66fa147c-869d-4e89-b386-186039d86361">
这是我在云服务器中按照常规方式安装yarn后的截图，还是卡在start yarn

**Comment by genchsusu** [comment]
你需要设置国内镜像源
然后再npm install -g yarn
然后yarn
然后yarn start

**Comment by BaJie041012** [comment]
在云服务器搞定了，非常谢谢各位大大，本地还是不太行，我不知道如何回复，直接回复一下[luzzhong](https://github.com/luzzhong)大大的问题把，就是纯菜，不会用Linux

另，log中有输出，但cmd窗口没有，是正常的吗
<img width="1280" alt="image" src="https://github.com/user-attachments/assets/29373423-3eac-41b2-a183-b699af80eb02">

**Comment by BaJie041012** [comment]
非常好的大佬，使我的感激之心旋转
