### ISSUE TITLE
游历貌似没有响应

### ISSUE THREAD

**Issue by xyloneX** [genchsusu/xddq-assistant#9]
[Client] Destiny 20653 {
  "isOneKey": true
}
Server没有返回

**Comment by genchsusu** [comment]
30分钟一次
2024-07-15 22:28:17.312 info   [Server] [仙友游历] [Power: 1] 一键游历

**Comment by xyloneX** [comment]
我调试了主动触发的，并没有效果

**Comment by genchsusu** [comment]
肯定有, 我几个号同时在用

**Comment by genchsusu** [comment]
返回是653

**Comment by xyloneX** [comment]
不知道为何我的不行，估计我等级太低且是新区

**Comment by genchsusu** [comment]
<img width="939" alt="image" src="https://github.com/user-attachments/assets/1628f12b-cfd1-4f0e-87d9-0995aa561e77">

**Comment by genchsusu** [comment]
砍树是给有分身的时候用的，，，我嫌烦，很多功能就没做。

**Comment by genchsusu** [comment]
你把"isOneKey": true 改成false就行了 然后加快它轮训速度

**Comment by xyloneX** [comment]
> 你把"isOneKey": true 改成false就行了 然后加快它轮训速度

改成false就可以了，666
